4.0
softawaregmbh/library-cqs pull request #10
Opened 2022-08-04 09:47 UTC by Skleni

Breaking changes in 4.0

* There is now an interface `ICommand<TResult>` for commands that return values. While this should be used sparingly, there are some cases where it can be useful.
* `ICommand` (which should be the default for implementing commands) derives from this new `ICommand<NoResult>` interface.
* There is now a common base interface for `IQuery<TResult>` and `ICommand<TResult>` (and thus `ICommand`): `IRequest<TResult`. This has the following advantages:
  * There is no need to distinguish between `IQueryHandler<TResult>` and `ICommandHandler` anymore. Simply use `IRequestHandler<TResult>`.
  * For cross-cutting concerns, you can write decorators that target `IRequestHandler<TResult>`. Before you had to write one for `IQueryHandler<TResult>` and one for `ICommandHandler`.
  * Instead of `IQueryProcessor` and `ICommandProcessor`, you can simply use `IRequestProcessor`.
* The cancellation token is now a required parameter for the `HandleAsync` method.

Because of these breaking changes, all package versions have been increased to the next common unused major version number 4.

2022-08-07 15:15 UTC, meinsiedler requested changes
Should we release a beta package first to test the 4.0 version in a "real" project?

2022-08-07 15:15 UTC, meinsiedler commented on src/softaware.Cqs/NoResult.cs
> +public record struct NoResult
`readonly` can be added.

2022-08-07 15:15 UTC, meinsiedler commented on src/softaware.Cqs/softaware.Cqs.csproj
> +    <NoWarn>CQ0001</NoWarn>
Why `NoWarn` for CQ0001 here?

2022-08-07 15:15 UTC, meinsiedler commented on src/softaware.Cqs.Analyzers.Tests/IRequestIsNotImplementedDirectlyAnalyzerTests.cs
> +    [InlineData("using softaware.Cqs; class Request : {|#0:IRequest<string>|} { }")]
Maybe add test case which tests the correct position of the diagnostic when implementing multiple interfaces or a base class?

2022-08-07 15:19 UTC, meinsiedler commented on src/softaware.Cqs.Analyzers.Tests/IRequestIsNotImplementedDirectlyAnalyzerTests.cs
> +                    MetadataReference.CreateFromFile("../../../../softaware.Cqs/bin/Debug/net6.0/softaware.Cqs.dll")
Unit tests are failing on build server, since we test in `Release` build and therefore, the path cannot be found.

2022-08-08 06:47 UTC, Skleni commented on README.md
> +        object type = typeof(TRequest).Name;
Because there is an overload `WriteLine(string? message, string? category);`

2022-08-08 06:55 UTC, Skleni commented on README.md
> +| [`softaware.CQS.Analyzers`](src/softaware.Cqs.Analyzers)                                                                             | [![NuGet](https://img.shields.io/nuget/v/softaware.CQS.Anaylze
Yes.

2022-08-08 07:07 UTC, Skleni commented on src/softaware.Cqs.DependencyInjection/DynamicRequestProcessor.cs
> +    public async Task<TResult> ExecuteAsync<TResult>(IRequest<TResult> request, CancellationToken cancellationToken)
Should we call the class `DynamicRequestHandler` then?

2022-08-08 07:14 UTC, meinsiedler commented on src/softaware.Cqs.DependencyInjection/DynamicRequestProcessor.cs
> +    public async Task<TResult> ExecuteAsync<TResult>(IRequest<TResult> request, CancellationToken cancellationToken)
I'm not sure if it would be confusing or charming, if we had an `IRequestProcessor` then, since we already have an `IRequestProcessor<,>`.

2022-08-08 07:18 UTC, Skleni commented on src/softaware.Cqs/softaware.Cqs.csproj
> +    <NoWarn>CQ0001</NoWarn>
Because `IQuery` and `ICommand` derive from `IRequest` ;)

2022-08-08 07:28 UTC, Skleni commented on src/softaware.Cqs.Decorators.Transaction/TransactionAwareRequestHandlerDecorator.cs
> +            IsolationLevel = IsolationLevel.ReadCommitted
Sounds good. Do you want to also include that in the 4.0 release?

2022-08-08 07:30 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.Transaction/TransactionAwareRequestHandlerDecorator.cs
> +            IsolationLevel = IsolationLevel.ReadCommitted
Yes, would be nice :)

2022-08-08 07:33 UTC, Skleni commented on src/softaware.Cqs.DependencyInjection/DynamicRequestProcessor.cs
> +    public async Task<TResult> ExecuteAsync<TResult>(IRequest<TResult> request, CancellationToken cancellationToken)
True.

2022-08-08 07:50 UTC, Skleni commented
I also thought about that. I already built packages manually and referenced them in the Template project via a directory Nuget source, but if you want we can also publish a prerelease-package. Do you have a project in mind we could use for testing?

2022-08-08 07:59 UTC, Skleni commented
And thanks for the extensive review :)

2022-08-22 08:16 UTC, meinsiedler approved these changes

2022-08-22 09:12 UTC, merged