Add CQS builder support and support for Microsoft DI
softawaregmbh/library-cqs pull request #5
Opened 2021-11-09 16:31 UTC by meinsiedler

* Adds support for `Microsoft.Extensions.DependencyInjection` DI framework
* Adds extension methods for Simple Injector's `Container` for fluent CQS configuration
* Adds NuGet packages for builder extensions for `Microsoft.Extensions.DependencyInjection`
* Tests refactored to test both Simple Injector and Microsoft DI

2021-11-09 16:33 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.FluentValidation/FluentValidationCommandHandlerDecorator.cs
> +            IEnumerable<IValidator<TCommand>> validators,
Refactored to inject `IEnumerable<IValidator>>` instead of one single validator. Needed for MS DI so that we don't need to conditionally register a fallback `NullValidator<T>>` if no validator is found for the `TCommand`. Now, when no validator is found, an empty collection is injected.

With this change, it is also now possible to support multiple validators for the same `TCommand`.

2021-11-10 06:28 UTC, meinsiedler commented on src/softaware.Cqs.DependencyInjection/softaware.Cqs.DependencyInjection.csproj
> +		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
To discuss: Should we use Version `6.0.0`?

2021-11-10 06:44 UTC, meinsiedler commented on src/softaware.Cqs.DependencyInjection/softaware.Cqs.DependencyInjection.csproj
> +		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
To discuss: Should we use Version `6.0.0`?

2021-11-10 08:16 UTC, Skleni requested changes

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs.Decorators.Transaction/softaware.Cqs.Decorators.Transaction.csproj
> +	<GenerateDocumentationFile>True</GenerateDocumentationFile>
Why is there a new version? Did something else change in this package?

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs.Decorators.UsageAware/softaware.Cqs.Decorators.UsageAware.csproj
> +    <FileVersion>2.1.1.0</FileVersion>
Is the version different on purpose?

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs.SimpleInjector/SoftawareCqsExtensions.cs
> +namespace softaware.Cqs
This is inconsistent with the `DependencyInjection` package.

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs.SimpleInjector/softaware.Cqs.SimpleInjector.xml
> -        <member name="T:softaware.Cqs.SimpleInjector.PublicCommandHandlerDecorator`1">
I think this file can be removed from source control.

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs.Tests/CommandAndQueryProcessorTest.cs
> +                    .AddDecorators(b => { });
Why is this necessary? Should we provide an overload without a parameter?

2021-11-10 08:16 UTC, Skleni commented on src/softaware.Cqs/softaware.Cqs.xml
> +        <member name="T:softaware.Cqs.PublicCommandHandlerDecorator`1">
This file can also be removed.

2021-11-10 08:29 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.FluentValidation/FluentValidationCommandHandlerDecorator.cs
> +﻿#nullable enable
I didn't want to enable it globally to keep the PR small(er) and enabled it in the meantime for some classes I touched anyway. I think I'll do another PR explicitly for enabling nullable everywhere.

2021-11-10 08:30 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.Transaction/softaware.Cqs.Decorators.Transaction.csproj
> +	<GenerateDocumentationFile>True</GenerateDocumentationFile>
Good catch, shouldn't be updated.

2021-11-10 08:30 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.UsageAware/softaware.Cqs.Decorators.UsageAware.csproj
> +    <FileVersion>2.1.1.0</FileVersion>
Good catch, shouldn't be updated.

2021-11-10 08:31 UTC, meinsiedler commented on src/softaware.Cqs.SimpleInjector/softaware.Cqs.SimpleInjector.xml
> -        <member name="T:softaware.Cqs.SimpleInjector.PublicCommandHandlerDecorator`1">
True. Was checked in before. I'll remove all XML doc files.

2021-11-10 08:34 UTC, meinsiedler commented on src/softaware.Cqs.Tests/CommandAndQueryProcessorTest.cs
> +                    .AddDecorators(b => { });
This is necessary to that the PublicCommand|QueryHandlerDecorators are added. This only applies to Simple Injector. We could add a `AddDecorators()` overload, but the `AddDecorators()` call would still be required and since we normally have at least some decorators like validation, I wasn't sure if the overload would actually be needed/used in practice.

2021-11-10 08:38 UTC, Skleni commented on src/softaware.Cqs.Tests/CommandAndQueryProcessorTest.cs
> +                    .AddDecorators(b => { });
Yeah, I meant the empty lambda. Not sure if it needed in practice.

2021-11-10 08:38 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.FluentValidation.DependencyInjection/SoftawareCqsFluentValidationDecoratorBuilderExtensions.cs
> +namespace SimpleInjector
Other packages which extend `Microsoft.Extensions.DependencyInjection` do use `Microsoft.Extensions.DependencyInjection` as namespace. But since the extension methods apply to the Simple Injector `Container` which is inside the `SimpleInjector` namespace, it is handy to use this namespace here as well, so that the extension methods are available on `this.container.AddSoftawareCqs(...)` without adding another `using` statement. So, our extension methods can easily be "found" be the developer, since the `using SimpleInjector` must already be available for the `Container`.

2021-11-10 08:41 UTC, Skleni commented on src/softaware.Cqs.Decorators.FluentValidation.DependencyInjection/SoftawareCqsFluentValidationDecoratorBuilderExtensions.cs
> +namespace SimpleInjector
But this is the `DependencyInjection` package, not the `SimpleInjector` one.

2021-11-10 08:41 UTC, meinsiedler commented on src/softaware.Cqs.SimpleInjector/SoftawareCqsExtensions.cs
> +namespace softaware.Cqs
I think I'll change to `SimpleInjector` namespace. Thoughts?

2021-11-10 08:43 UTC, meinsiedler commented on src/softaware.Cqs.Decorators.FluentValidation.DependencyInjection/SoftawareCqsFluentValidationDecoratorBuilderExtensions.cs
> +namespace SimpleInjector
Then, this is is nonsense anyways 😅 I'll change to `Microsoft.Extensions.DependencyInjection`.

2021-11-10 10:03 UTC, merged