Add example how to use validation decorators with simple injector
softawaregmbh/library-cqs pull request #8
Opened 2022-01-10 18:04 UTC by d-bauer

2022-01-11 07:13 UTC, meinsiedler requested changes

2022-01-11 07:13 UTC, meinsiedler commented on README.md
> +    .AddDecorators(b => b.AddCommandHandlerDecorator(typeof(ValidationCommandHandlerDecorator<>)))
You can chain the calls to `AddCommandHandlerDecorator(...)` and `AddQueryHandlerDecorator(...)` within the `AddDecorators(...)` method, so you don't need to call `AddDecorators(...)` multiple times:

```csharp
this.container
   .AddSoftawareCqs(b => b.IncludeTypesFrom(Assembly.GetExecutingAssembly()))
   .AddDecorators(b => b
      // (1) Add Validation Decorators
      .AddQueryHandlerDecorator(typeof(ValidationQueryHandlerDecorator<,>))
      .AddCommandHandlerDecorator(typeof(ValidationCommandHandlerDecorator<>))
      // (2) Add FluentValidation Decorators
      .AddQueryHandlerDecorator(typeof(FluentValidationQueryHandlerDecorator<,>))
      .AddCommandHandlerDecorator(typeof(FluentValidationCommandHandlerDecorator<>)));
```

This should be the way to go, since the `AddDecorators(...)` call internally adds some logic at the end of the method execution and this logic would be executed multiple times if the `AddDecorators(...)` would be called multiple times.

2022-01-13 15:26 UTC, d-bauer commented on README.md
> +    .AddDecorators(b => b.AddCommandHandlerDecorator(typeof(ValidationCommandHandlerDecorator<>)))
I changed the text accordingly 👍

2022-01-13 15:27 UTC, meinsiedler approved these changes

2022-01-13 15:27 UTC, merged